# Generated by Django 4.2.7 on 2023-12-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0002_alter_state_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
