# Generated by Django 4.2.7 on 2023-12-05 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0004_village_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='village',
            name='circleName',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='village',
            name='deliveryStatus',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='village',
            name='divisionName',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='village',
            name='regionName',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='village',
            name='relatedHeadoffice',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='village',
            name='relatedSuboffice',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='village',
            name='telephone',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='village',
            name='villageType',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
