# Generated by Django 4.2.8 on 2023-12-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0006_data_alter_district_name_city_data_district_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
