# Generated by Django 4.2.8 on 2023-12-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0008_alter_data_area_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='area_name',
            field=models.CharField(max_length=50),
        ),
    ]
