# Generated by Django 4.2.8 on 2023-12-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0010_city_rural_data_city_urban_data_data_district_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='total_workers_females',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
