# Generated by Django 4.2.8 on 2023-12-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0012_alter_data_caste_popul_females_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='state_code',
            field=models.CharField(default='', max_length=30),
        ),
    ]
