# Generated by Django 4.2.8 on 2023-12-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0013_state_state_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='district_code',
            field=models.CharField(default='', max_length=30),
        ),
    ]
