# Generated by Django 4.2.8 on 2023-12-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0014_district_district_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='city_code',
            field=models.CharField(default='', max_length=30),
        ),
    ]
