# Generated by Django 4.2.8 on 2023-12-13 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0016_village_village_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
