# Generated by Django 4.2.8 on 2023-12-13 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0022_village_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='village',
            name='slug',
        ),
    ]
