# Generated by Django 4.2.8 on 2023-12-13 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0029_village_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='village',
            name='slug',
        ),
    ]
