# Generated by Django 4.2.8 on 2023-12-14 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0030_remove_village_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='data',
        ),
        migrations.RemoveField(
            model_name='city',
            name='rural_data',
        ),
        migrations.RemoveField(
            model_name='city',
            name='urban_data',
        ),
        migrations.RemoveField(
            model_name='district',
            name='data',
        ),
        migrations.RemoveField(
            model_name='district',
            name='rural_data',
        ),
        migrations.RemoveField(
            model_name='district',
            name='urban_data',
        ),
        migrations.RemoveField(
            model_name='state',
            name='data',
        ),
        migrations.RemoveField(
            model_name='state',
            name='rural_data',
        ),
        migrations.RemoveField(
            model_name='state',
            name='urban_data',
        ),
        migrations.RemoveField(
            model_name='village',
            name='data',
        ),
        migrations.RemoveField(
            model_name='village',
            name='rural_data',
        ),
        migrations.RemoveField(
            model_name='village',
            name='urban_data',
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_years', to='census.city')),
                ('data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_year', to='census.data')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='district_years', to='census.district')),
                ('rural_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rural_data_year', to='census.data')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state_years', to='census.state')),
                ('urban_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='urban_data_year', to='census.data')),
                ('village', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='village_years', to='census.village')),
            ],
        ),
    ]
