# Generated by Django 4.2.8 on 2023-12-15 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0031_remove_city_data_remove_city_rural_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='village',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
